name: API MOVIES CI

on: [push]

defaults:
  run:
    working-directory: ./src

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: install
        shell: bash
        run: npm ci
      - name: run unit test
        shell: bash
        run: npm test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: install
        shell: bash
        run: npm ci
      - name: run lint
        shell: bash
        run: npm run lint --silent
  
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:18

    services:
      mongo-e2e:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: test
          MONGO_INITDB_ROOT_PASSWORD: test123

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        shell: bash
        run: npm ci
      - name: run e2e
        shell: bash
        run: npm run test:e2e
        env:
          DB_NAME_TEST: db-movies-test
          DB_USER: test
          DB_PASSWORD: test123
          DB_HOST: mongo-e2e