name: API MOVIES CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

defaults:
  run:
    working-directory: ./src

jobs:
  avoid-reduncy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Cancel parallel jobs
        uses: actions/checkout@v4

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install
        shell: bash
        run: npm ci
      - name: run lint
        shell: bash
        run: npm run lint --silent

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install
        shell: bash
        run: npm ci
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  unit-test:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install
        shell: bash
        run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: run unit test
        shell: bash
        run: npm test

  e2e:
    needs: [lint, build]
    runs-on: ubuntu-latest
    # container:
    #   image: node:18

    # services:
    #   mongo-e2e:
    #     image: mongo:6
    #     ports:
    #       - 27017:27017
    #     env:
    #       MONGO_INITDB_ROOT_USERNAME: test
    #       MONGO_INITDB_ROOT_PASSWORD: test123
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        shell: bash
        run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: run e2e
        shell: bash
        run: npm run test:e2e
        env:
          DB_NAME_TEST: ${{ vars.DB_NAME_TEST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}

  deploy:
    needs: [unit-test, e2e]
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy
        run: echo 'Here do the deploy'
